use confluent.version 5.3.1, workaround for avro version conflicts. java.lang.NoSuchMethodError: org.apache.avro.Schema.setValidateDefaults(Z)Lorg/apache/avro/Schema. because 5.4.2 version CachedSchemaRegistryClient use parser.setValidateDefaults(false) method